// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.handge.proto;

public interface PacketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.handge.proto.Packet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *传输层协议
   * </pre>
   *
   * <code>string ipPorto2Name = 1;</code>
   */
  java.lang.String getIpPorto2Name();
  /**
   * <pre>
   *传输层协议
   * </pre>
   *
   * <code>string ipPorto2Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpPorto2NameBytes();

  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>string srcIp = 2;</code>
   */
  java.lang.String getSrcIp();
  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>string srcIp = 2;</code>
   */
  com.google.protobuf.ByteString
      getSrcIpBytes();

  /**
   * <pre>
   *源端口
   * </pre>
   *
   * <code>uint32 srcPort = 3;</code>
   */
  int getSrcPort();

  /**
   * <pre>
   *目的IP
   * </pre>
   *
   * <code>string dstIp = 4;</code>
   */
  java.lang.String getDstIp();
  /**
   * <pre>
   *目的IP
   * </pre>
   *
   * <code>string dstIp = 4;</code>
   */
  com.google.protobuf.ByteString
      getDstIpBytes();

  /**
   * <pre>
   *目的端口
   * </pre>
   *
   * <code>uint32 dstPort = 5;</code>
   */
  int getDstPort();
}
