// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package com.handge.proto;

/**
 * Protobuf type {@code com.handge.proto.Packet}
 */
public  final class Packet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.handge.proto.Packet)
    PacketOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Packet.newBuilder() to construct.
  private Packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Packet() {
    ipPorto2Name_ = "";
    srcIp_ = "";
    srcPort_ = 0;
    dstIp_ = "";
    dstPort_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Packet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ipPorto2Name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            srcIp_ = s;
            break;
          }
          case 24: {

            srcPort_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            dstIp_ = s;
            break;
          }
          case 40: {

            dstPort_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.handge.proto.PacketOuterClass.internal_static_com_handge_proto_Packet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.handge.proto.PacketOuterClass.internal_static_com_handge_proto_Packet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.handge.proto.Packet.class, com.handge.proto.Packet.Builder.class);
  }

  public static final int IPPORTO2NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object ipPorto2Name_;
  /**
   * <pre>
   *传输层协议
   * </pre>
   *
   * <code>string ipPorto2Name = 1;</code>
   */
  public java.lang.String getIpPorto2Name() {
    java.lang.Object ref = ipPorto2Name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ipPorto2Name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *传输层协议
   * </pre>
   *
   * <code>string ipPorto2Name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIpPorto2NameBytes() {
    java.lang.Object ref = ipPorto2Name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ipPorto2Name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRCIP_FIELD_NUMBER = 2;
  private volatile java.lang.Object srcIp_;
  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>string srcIp = 2;</code>
   */
  public java.lang.String getSrcIp() {
    java.lang.Object ref = srcIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>string srcIp = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSrcIpBytes() {
    java.lang.Object ref = srcIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRCPORT_FIELD_NUMBER = 3;
  private int srcPort_;
  /**
   * <pre>
   *源端口
   * </pre>
   *
   * <code>uint32 srcPort = 3;</code>
   */
  public int getSrcPort() {
    return srcPort_;
  }

  public static final int DSTIP_FIELD_NUMBER = 4;
  private volatile java.lang.Object dstIp_;
  /**
   * <pre>
   *目的IP
   * </pre>
   *
   * <code>string dstIp = 4;</code>
   */
  public java.lang.String getDstIp() {
    java.lang.Object ref = dstIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dstIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *目的IP
   * </pre>
   *
   * <code>string dstIp = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDstIpBytes() {
    java.lang.Object ref = dstIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dstIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DSTPORT_FIELD_NUMBER = 5;
  private int dstPort_;
  /**
   * <pre>
   *目的端口
   * </pre>
   *
   * <code>uint32 dstPort = 5;</code>
   */
  public int getDstPort() {
    return dstPort_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIpPorto2NameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ipPorto2Name_);
    }
    if (!getSrcIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, srcIp_);
    }
    if (srcPort_ != 0) {
      output.writeUInt32(3, srcPort_);
    }
    if (!getDstIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dstIp_);
    }
    if (dstPort_ != 0) {
      output.writeUInt32(5, dstPort_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIpPorto2NameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ipPorto2Name_);
    }
    if (!getSrcIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, srcIp_);
    }
    if (srcPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, srcPort_);
    }
    if (!getDstIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dstIp_);
    }
    if (dstPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, dstPort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.handge.proto.Packet)) {
      return super.equals(obj);
    }
    com.handge.proto.Packet other = (com.handge.proto.Packet) obj;

    boolean result = true;
    result = result && getIpPorto2Name()
        .equals(other.getIpPorto2Name());
    result = result && getSrcIp()
        .equals(other.getSrcIp());
    result = result && (getSrcPort()
        == other.getSrcPort());
    result = result && getDstIp()
        .equals(other.getDstIp());
    result = result && (getDstPort()
        == other.getDstPort());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IPPORTO2NAME_FIELD_NUMBER;
    hash = (53 * hash) + getIpPorto2Name().hashCode();
    hash = (37 * hash) + SRCIP_FIELD_NUMBER;
    hash = (53 * hash) + getSrcIp().hashCode();
    hash = (37 * hash) + SRCPORT_FIELD_NUMBER;
    hash = (53 * hash) + getSrcPort();
    hash = (37 * hash) + DSTIP_FIELD_NUMBER;
    hash = (53 * hash) + getDstIp().hashCode();
    hash = (37 * hash) + DSTPORT_FIELD_NUMBER;
    hash = (53 * hash) + getDstPort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.handge.proto.Packet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.handge.proto.Packet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.handge.proto.Packet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.handge.proto.Packet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.handge.proto.Packet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.handge.proto.Packet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.handge.proto.Packet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.handge.proto.Packet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.handge.proto.Packet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.handge.proto.Packet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.handge.proto.Packet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.handge.proto.Packet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.handge.proto.Packet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.handge.proto.Packet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.handge.proto.Packet)
      com.handge.proto.PacketOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.handge.proto.PacketOuterClass.internal_static_com_handge_proto_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.handge.proto.PacketOuterClass.internal_static_com_handge_proto_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.handge.proto.Packet.class, com.handge.proto.Packet.Builder.class);
    }

    // Construct using com.handge.proto.Packet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ipPorto2Name_ = "";

      srcIp_ = "";

      srcPort_ = 0;

      dstIp_ = "";

      dstPort_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.handge.proto.PacketOuterClass.internal_static_com_handge_proto_Packet_descriptor;
    }

    @java.lang.Override
    public com.handge.proto.Packet getDefaultInstanceForType() {
      return com.handge.proto.Packet.getDefaultInstance();
    }

    @java.lang.Override
    public com.handge.proto.Packet build() {
      com.handge.proto.Packet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.handge.proto.Packet buildPartial() {
      com.handge.proto.Packet result = new com.handge.proto.Packet(this);
      result.ipPorto2Name_ = ipPorto2Name_;
      result.srcIp_ = srcIp_;
      result.srcPort_ = srcPort_;
      result.dstIp_ = dstIp_;
      result.dstPort_ = dstPort_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.handge.proto.Packet) {
        return mergeFrom((com.handge.proto.Packet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.handge.proto.Packet other) {
      if (other == com.handge.proto.Packet.getDefaultInstance()) return this;
      if (!other.getIpPorto2Name().isEmpty()) {
        ipPorto2Name_ = other.ipPorto2Name_;
        onChanged();
      }
      if (!other.getSrcIp().isEmpty()) {
        srcIp_ = other.srcIp_;
        onChanged();
      }
      if (other.getSrcPort() != 0) {
        setSrcPort(other.getSrcPort());
      }
      if (!other.getDstIp().isEmpty()) {
        dstIp_ = other.dstIp_;
        onChanged();
      }
      if (other.getDstPort() != 0) {
        setDstPort(other.getDstPort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.handge.proto.Packet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.handge.proto.Packet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ipPorto2Name_ = "";
    /**
     * <pre>
     *传输层协议
     * </pre>
     *
     * <code>string ipPorto2Name = 1;</code>
     */
    public java.lang.String getIpPorto2Name() {
      java.lang.Object ref = ipPorto2Name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipPorto2Name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *传输层协议
     * </pre>
     *
     * <code>string ipPorto2Name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpPorto2NameBytes() {
      java.lang.Object ref = ipPorto2Name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipPorto2Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *传输层协议
     * </pre>
     *
     * <code>string ipPorto2Name = 1;</code>
     */
    public Builder setIpPorto2Name(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ipPorto2Name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *传输层协议
     * </pre>
     *
     * <code>string ipPorto2Name = 1;</code>
     */
    public Builder clearIpPorto2Name() {
      
      ipPorto2Name_ = getDefaultInstance().getIpPorto2Name();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *传输层协议
     * </pre>
     *
     * <code>string ipPorto2Name = 1;</code>
     */
    public Builder setIpPorto2NameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ipPorto2Name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object srcIp_ = "";
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>string srcIp = 2;</code>
     */
    public java.lang.String getSrcIp() {
      java.lang.Object ref = srcIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>string srcIp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSrcIpBytes() {
      java.lang.Object ref = srcIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>string srcIp = 2;</code>
     */
    public Builder setSrcIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>string srcIp = 2;</code>
     */
    public Builder clearSrcIp() {
      
      srcIp_ = getDefaultInstance().getSrcIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>string srcIp = 2;</code>
     */
    public Builder setSrcIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcIp_ = value;
      onChanged();
      return this;
    }

    private int srcPort_ ;
    /**
     * <pre>
     *源端口
     * </pre>
     *
     * <code>uint32 srcPort = 3;</code>
     */
    public int getSrcPort() {
      return srcPort_;
    }
    /**
     * <pre>
     *源端口
     * </pre>
     *
     * <code>uint32 srcPort = 3;</code>
     */
    public Builder setSrcPort(int value) {
      
      srcPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *源端口
     * </pre>
     *
     * <code>uint32 srcPort = 3;</code>
     */
    public Builder clearSrcPort() {
      
      srcPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dstIp_ = "";
    /**
     * <pre>
     *目的IP
     * </pre>
     *
     * <code>string dstIp = 4;</code>
     */
    public java.lang.String getDstIp() {
      java.lang.Object ref = dstIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *目的IP
     * </pre>
     *
     * <code>string dstIp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDstIpBytes() {
      java.lang.Object ref = dstIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *目的IP
     * </pre>
     *
     * <code>string dstIp = 4;</code>
     */
    public Builder setDstIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dstIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目的IP
     * </pre>
     *
     * <code>string dstIp = 4;</code>
     */
    public Builder clearDstIp() {
      
      dstIp_ = getDefaultInstance().getDstIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目的IP
     * </pre>
     *
     * <code>string dstIp = 4;</code>
     */
    public Builder setDstIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dstIp_ = value;
      onChanged();
      return this;
    }

    private int dstPort_ ;
    /**
     * <pre>
     *目的端口
     * </pre>
     *
     * <code>uint32 dstPort = 5;</code>
     */
    public int getDstPort() {
      return dstPort_;
    }
    /**
     * <pre>
     *目的端口
     * </pre>
     *
     * <code>uint32 dstPort = 5;</code>
     */
    public Builder setDstPort(int value) {
      
      dstPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *目的端口
     * </pre>
     *
     * <code>uint32 dstPort = 5;</code>
     */
    public Builder clearDstPort() {
      
      dstPort_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.handge.proto.Packet)
  }

  // @@protoc_insertion_point(class_scope:com.handge.proto.Packet)
  private static final com.handge.proto.Packet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.handge.proto.Packet();
  }

  public static com.handge.proto.Packet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Packet>
      PARSER = new com.google.protobuf.AbstractParser<Packet>() {
    @java.lang.Override
    public Packet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Packet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Packet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Packet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.handge.proto.Packet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

