// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.handge.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.handge.proto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 age = 2;</code>
   */
  int getAge();
}
